plugins {
    id 'com.android.application'
}

android {
    namespace 'org.jpi59.ethiccompass'
    compileSdk 36

    defaultConfig {
        applicationId 'org.jpi59.ethiccompass'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            vcsInfo {
                include = false
            }
        }
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
}
